import type { NextPage } from "next";
import Head from 'next/head'
import {inject, observer} from "mobx-react";
import React from "react";
import PageProps from "../PageProps";


const Login: any = inject("rootStore")(
  observer((props: PageProps) => {

    return (
      <div>
        <Head>
          <title>{ props.rootStore?.title }</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <form>
          <label htmlFor="username">Username:</label>
          <input id="username" />
        </form>
      </div>
    );
  })
);

export default Login;