import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import {inject, observer} from "mobx-react"
import { useRouter, withRouter } from 'next/router'
import React, {useEffect} from "react";
import RootStore from "../store/RootStore";
import UserStore from "../store/UserStore";
import PageProps from "../services/interfaces/PageProps";
import loginRedirect from "../effects/LoginRedirect.effect";
import Navigation from "../components/navigation";
import PostStore from "../store/PostStore";

@inject('rootStore', 'userStore', 'postStore')
@observer
class HomePage extends React.Component<PageProps> {
  constructor(props: PageProps) {
    super(props);
  }

  componentDidMount() {
    loginRedirect(this.props.userStore?.isLoggedIn!, this.props.router);
  }

  render() {
    if (this.props.userStore?.isLoggedIn) {
      return (
        <div className="page-style">
          <Head>
            <title>Dashboard | {this.props.rootStore?.title}</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
          </Head>

          <Navigation
            permissionsLevel={this.props.userStore?.user.permissionsLevel!}
            postTypes={this.props.postStore?.postTypes!}
            activePage={"dashboard"}
            rootStore={this.props.rootStore!}
          />
          <main>
            <h1>Dashboard</h1>
          </main>
        </div>
      );
    }
    return (<div className={"loading"}/>);
  }
}

export default withRouter(HomePage);
