import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import {inject, observer} from "mobx-react"
import { useRouter } from 'next/router'
import React, {useEffect} from "react";
import RootStore from "../store/RootStore";
import UserStore from "../store/UserStore";
import PageProps from "./PageProps";
import useLoginRedirectEffect from "../effects/LoginRedirect.effect";

const Home: any = inject("rootStore")(
  observer((props: PageProps) => {
    const rootStore: RootStore = props.rootStore!;
    const userStore: UserStore = props.rootStore?.userStore!;
    const router = useRouter();

    // When screens are ready, deal with login
    // useEffect(() => useLoginRedirectEffect(userStore.isLoggedIn, router));

    return (
      <div>
        <Head>
          <title>{ rootStore.title }</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <h1>My first Medium article</h1>
      </div>
    );
  })
);

export default Home;
