import styles from './login.page.module.css';
import Head from 'next/head'
import {inject, observer} from "mobx-react";
import React from "react";
import PageProps from "../../../services/interfaces/PageProps";

@inject('rootStore', 'userStore', 'postStore')
@observer
class PostPage extends React.Component<PageProps> {
  render() {
    return (
      <div className={'page-style'}>
        <Head>
          <title>Post | { this.props.rootStore?.title }</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <style jsx>{`
        
        `}</style>

        <main>
          <h1>Edit post</h1>
        </main>
      </div>
    );
  }
}

export default PostPage;